import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import postsRouter from "./posts";
import commentsRouter from "./comments";
import streamsRouter from "./streams";
import messagesRouter from "./messages";
import walletRouter from "./wallet";
import hashtagsRouter from "./hashtags";
import notificationsRouter from "./notifications";
import bookmarksRouter from "./bookmarks";
import meetupsRouter from "./meetups";
import marketplaceRouter from "./marketplace";
import auctionsRouter from "./auctions";
import merchRouter from "./merch";
import muxRouter from "./mux";
import uploadRouter from "./upload";
import adminRouter from "./admin";
import subscriptionsRouter from "./subscriptions";
import repostsRouter from "./reposts";
import categoriesRouter from "./categories";
import shopRouter from "./shop";
import suggestBioRouter from "./suggestBio";
import paidContentRouter from "./paidContent";
import takedownRouter from "./takedown";
import printifyRouter from "./printify";
import bugReportsRouter from "./bugReports";
import creatorLinksRouter from "./creatorLinks";
import gifsRouter from "./gifs";
import muxWebhookRouter from "./muxWebhook";
import reportsRouter from "./reports";
import hiveRouter from "./hive";
import linkPreviewRouter from "./linkPreview";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(bookmarksRouter);
router.use(postsRouter);
router.use(commentsRouter);
router.use(streamsRouter);
router.use(messagesRouter);
router.use(walletRouter);
router.use(hashtagsRouter);
router.use(notificationsRouter);
router.use(meetupsRouter);
router.use(marketplaceRouter);
router.use(auctionsRouter);
router.use(merchRouter);
router.use(muxRouter);
router.use(muxWebhookRouter);
router.use(uploadRouter);
router.use(categoriesRouter);
router.use(shopRouter);
router.use(suggestBioRouter);
router.use(creatorLinksRouter);
router.use(gifsRouter);
router.use(adminRouter);
router.use(subscriptionsRouter);
router.use(repostsRouter);
router.use(paidContentRouter);
router.use(takedownRouter);
router.use(printifyRouter);
router.use(bugReportsRouter);
router.use(reportsRouter);
router.use(hiveRouter);
router.use(linkPreviewRouter);

export default router;
